/* -------------------------------------------------------------------------- */
/*  MENUS (unchanged)                                                         */
/* -------------------------------------------------------------------------- */

export const MENUS = [
    { label: 'Shop by', items: ['New Arrivals', 'Best Sellers', 'All T-Shirts', 'Sale'] },
    {
      label: 'Category',
      items: ['Regular Fit', 'Oversized Fit', "Men's Polo", "Men's Gym Vest", "Men's sweatshirts"],
    },
    {
      label: 'Collections',
      items: ['Solid', 'Printed', 'Minimalist', 'Streetwear', 'Aesthetic', 'puff', 'Acid Washed', 'supima'],
    },
   
  ] as const;
  
  /* Helper left here in case other files import it */
  export const slugify = (s: string) => encodeURIComponent(s.toLowerCase().replace(/\s+/g, '-'));
  
  /* -------------------------------------------------------------------------- */
  /*  Product type (single variant baked-in)                                    */
  /* -------------------------------------------------------------------------- */
  export interface Product {
    id: number;
    title: string;
    subtitle: string;
    price: number;
    img: string;      // hero / card photo
    label: string;    // slugified top-level menu
    item: string;     // slugified sub-item
    color: string;
    size: string;
    image: string;    // secondary/icon image ⇒ '/images/default.svg'
  }
  const IMAGE_POOL = [
  'M-1.png',  'M-7.png',  'M-8.png',  'M-10.png', 'M-11.png',
  'M-12.png', 'M-13.png', 'M-14.png', 'M-15.png',
  
  'mockup 3.png', 'mockup 5.png', 'mockup 6.png',
] as const;
  
  /* -------------------------------------------------------------------------- */
  /*  Hard-coded PRODUCTS array (24 entries – one per menu item)                */
  /* -------------------------------------------------------------------------- */
  export const preProduct: Product[] = [
    {
      id: 1,
      title: "New Arrivals Tee 1",
      subtitle: "New Arrivals",
      price: 799,
      img: "/images/mock/product1.jpg",
      label: "shop",
      item: "new-arrivals",
      color: "Black",
      size: "M",
      image: "/images/default.svg",
    },
    {
      id: 2,
      title: "Best Seller Tee 1",
      subtitle: "Best Sellers",
      price: 899,
      img: "/images/mock/product2.jpg",
      label: "shop",
      item: "best-sellers",
      color: "White",
      size: "L",
      image: "/images/M-13.png",
    },
    {
      id: 3,
      title: "Essential Tee 1",
      subtitle: "All T-Shirts",
      price: 699,
      img: "/images/mock/product3.jpg",
      label: "shop",
      item: "all-t-shirts",
      color: "Navy",
      size: "S",
      image: "/images/default.svg",
    },
    {
      id: 4,
      title: "Seasonal Sale Tee 1",
      subtitle: "Sale",
      price: 599,
      img: "/images/mock/product4.jpg",
      label: "shop",
      item: "sale",
      color: "Olive",
      size: "XL",
      image: "/images/default.svg",
    },
    {
      id: 5,
      title: "Street Graphic Tee 1",
      subtitle: "Graphic Tees",
      price: 999,
      img: "/images/mock/product1.jpg",
      label: "styles",
      item: "graphic-tees",
      color: "Maroon",
      size: "M",
      image: "/images/default.svg",
    },
    {
      id: 6,
      title: "Everyday Plain Tee 1",
      subtitle: "Plain Tees",
      price: 749,
      img: "/images/mock/product2.jpg",
      label: "styles",
      item: "plain-tees",
      color: "Grey",
      size: "L",
      image: "/images/default.svg",
    },
    {
      id: 7,
      title: "Comfy Oversized Tee 1",
      subtitle: "Oversized Tees",
      price: 1099,
      img: "/images/mock/product3.jpg",
      label: "styles",
      item: "oversized-tees",
      color: "White",
      size: "XL",
      image: "/images/default.svg",
    },
    {
      id: 8,
      title: "Slim-Fit Training Tee 1",
      subtitle: "Slim Fit Tees",
      price: 899,
      img: "/images/mock/product4.jpg",
      label: "styles",
      item: "slim-fit-tees",
      color: "Black",
      size: "S",
      image: "/images/default.svg",
    },
    {
      id: 9,
      title: "Athleisure Sport Tee 1",
      subtitle: "Athleisure",
      price: 949,
      img: "/images/mock/product1.jpg",
      label: "styles",
      item: "athleisure",
      color: "Olive",
      size: "M",
      image: "/images/default.svg",
    },
    {
      id: 10,
      title: "Urban Streetwear Tee 1",
      subtitle: "Streetwear",
      price: 1199,
      img: "/images/mock/product2.jpg",
      label: "collections",
      item: "streetwear",
      color: "Black",
      size: "L",
      image: "/images/default.svg",
    },
    {
      id: 11,
      title: "Clean Minimalist Tee 1",
      subtitle: "Minimalist",
      price: 899,
      img: "/images/mock/product3.jpg",
      label: "collections",
      item: "minimalist",
      color: "White",
      size: "M",
      image: "/images/default.svg",
    },
    {
      id: 12,
      title: "Bold Prints Tee 1",
      subtitle: "Bold Prints",
      price: 999,
      img: "/images/mock/product4.jpg",
      label: "collections",
      item: "bold-prints",
      color: "Bright Red",
      size: "S",
      image: "/images/default.svg",
    },
    {
      id: 13,
      title: "Retro Vintage Tee 1",
      subtitle: "Vintage Vibes",
      price: 1099,
      img: "/images/mock/product1.jpg",
      label: "collections",
      item: "vintage-vibes",
      color: "Beige",
      size: "XL",
      image: "/images/default.svg",
    },
    {
      id: 14,
      title: "Premium Collection Tee 1",
      subtitle: "Premium Collection",
      price: 1399,
      img: "/images/mock/product2.jpg",
      label: "collections",
      item: "premium-collection",
      color: "Navy",
      size: "L",
      image: "/images/default.svg",
    },
    {
      id: 15,
      title: "Limited Edition Tee 1",
      subtitle: "Limited Edition",
      price: 1499,
      img: "/images/mock/product3.jpg",
      label: "collections",
      item: "limited-edition",
      color: "Maroon",
      size: "M",
      image: "/images/default.svg",
    },
    {
      id: 16,
      title: "All-Black Tee 1",
      subtitle: "Black",
      price: 799,
      img: "/images/mock/product4.jpg",
      label: "shop-by-color",
      item: "black",
      color: "Black",
      size: "XL",
      image: "/images/default.svg",
    },
    {
      id: 17,
      title: "Pure White Tee 1",
      subtitle: "White",
      price: 799,
      img: "/images/mock/product1.jpg",
      label: "shop-by-color",
      item: "white",
      color: "White",
      size: "M",
      image: "/images/default.svg",
    },
    {
      id: 18,
      title: "Soft Neutral Tee 1",
      subtitle: "Neutrals",
      price: 849,
      img: "/images/mock/product2.jpg",
      label: "shop-by-color",
      item: "neutrals",
      color: "Beige",
      size: "L",
      image: "/images/default.svg",
    },
    {
      id: 19,
      title: "Earth Tone Tee 1",
      subtitle: "Earth Tones",
      price: 899,
      img: "/images/mock/product3.jpg",
      label: "shop-by-color",
      item: "earth-tones",
      color: "Olive",
      size: "S",
      image: "/images/default.svg",
    },
    {
      id: 20,
      title: "Bright Pop Tee 1",
      subtitle: "Brights",
      price: 949,
      img: "/images/mock/product4.jpg",
      label: "shop-by-color",
      item: "brights",
      color: "Bright Blue",
      size: "M",
      image: "/images/default.svg",
    },
    {
      id: 21,
      title: "Everyday Comfort Tee 1",
      subtitle: "Everyday Wear",
      price: 699,
      img: "/images/mock/product1.jpg",
      label: "shop-by-occasion",
      item: "everyday-wear",
      color: "Grey",
      size: "L",
      image: "/images/default.svg",
    },
    {
      id: 22,
      title: "Night-Out Tee 1",
      subtitle: "Night Out",
      price: 999,
      img: "/images/mock/product2.jpg",
      label: "shop-by-occasion",
      item: "night-out",
      color: "Black",
      size: "M",
      image: "/images/default.svg",
    },
    {
      id: 23,
      title: "Smart Workwear Tee 1",
      subtitle: "Workwear",
      price: 1099,
      img: "/images/mock/product3.jpg",
      label: "shop-by-occasion",
      item: "workwear",
      color: "Navy",
      size: "XL",
      image: "/images/default.svg",
    },
    {
      id: 24,
      title: "Chill Lounge Tee 1",
      subtitle: "Lounge / Home",
      price: 799,
      img: "/images/mock/product4.jpg",
      label: "shop-by-occasion",
      item: "lounge-home",
      color: "Beige",
      size: "S",
      image: "/images/default.svg",
    },
    {
      id: 25,
      title: "New Arrivals Tee 2",
      subtitle: "New Arrivals",
      price: 699,
      img: "/images/mock/product1.jpg",
      label: "shop",
      item: "new-arrivals",
      color: "White",
      size: "XL",
      image: "/images/default.svg",
    },
    {
      id: 26,
      title: "Best Seller Tee 2",
      subtitle: "Best Sellers",
      price: 899,
      img: "/images/mock/product2.jpg",
      label: "shop",
      item: "best-sellers",
      color: "Maroon",
      size: "M",
      image: "/images/default.svg",
    },
    {
      id: 27,
      title: "Essential Tee 2",
      subtitle: "All T-Shirts",
      price: 799,
      img: "/images/mock/product3.jpg",
      label: "shop",
      item: "all-t-shirts",
      color: "Grey",
      size: "L",
      image: "/images/default.svg",
    },
    {
      id: 28,
      title: "Seasonal Sale Tee 2",
      subtitle: "Sale",
      price: 599,
      img: "/images/mock/product4.jpg",
      label: "shop",
      item: "sale",
      color: "Bright Blue",
      size: "S",
      image: "/images/default.svg",
    },
    {
      id: 29,
      title: "Street Graphic Tee 2",
      subtitle: "Graphic Tees",
      price: 1049,
      img: "/images/mock/product1.jpg",
      label: "styles",
      item: "graphic-tees",
      color: "Black",
      size: "M",
      image: "/images/default.svg",
    },
    {
      id: 30,
      title: "Everyday Plain Tee 2",
      subtitle: "Plain Tees",
      price: 749,
      img: "/images/mock/product2.jpg",
      label: "styles",
      item: "plain-tees",
      color: "White",
      size: "S",
      image: "/images/default.svg",
    },
    {
      id: 31,
      title: "Comfy Oversized Tee 2",
      subtitle: "Oversized Tees",
      price: 1199,
      img: "/images/mock/product3.jpg",
      label: "styles",
      item: "oversized-tees",
      color: "Olive",
      size: "XL",
      image: "/images/default.svg",
    },
    {
      id: 32,
      title: "Slim-Fit Training Tee 2",
      subtitle: "Slim Fit Tees",
      price: 899,
      img: "/images/mock/product4.jpg",
      label: "styles",
      item: "slim-fit-tees",
      color: "Beige",
      size: "L",
      image: "/images/default.svg",
    },
    {
      id: 33,
      title: "Athleisure Sport Tee 2",
      subtitle: "Athleisure",
      price: 949,
      img: "/images/mock/product1.jpg",
      label: "styles",
      item: "athleisure",
      color: "Grey",
      size: "M",
      image: "/images/default.svg",
    },
    {
      id: 34,
      title: "Urban Streetwear Tee 2",
      subtitle: "Streetwear",
      price: 1199,
      img: "/images/mock/product2.jpg",
      label: "collections",
      item: "streetwear",
      color: "Bright Blue",
      size: "M",
      image: "/images/default.svg",
    },
    {
      id: 35,
      title: "Clean Minimalist Tee 2",
      subtitle: "Minimalist",
      price: 899,
      img: "/images/mock/product3.jpg",
      label: "collections",
      item: "minimalist",
      color: "Black",
      size: "XXL",
      image: "/images/default.svg",
    },
    {
      id: 36,
      title: "Bold Prints Tee 2",
      subtitle: "Bold Prints",
      price: 1099,
      img: "/images/mock/product4.jpg",
      label: "collections",
      item: "bold-prints",
      color: "White",
      size: "L",
      image: "/images/default.svg",
    },
    {
      id: 37,
      title: "Retro Vintage Tee 2",
      subtitle: "Vintage Vibes",
      price: 1099,
      img: "/images/mock/product1.jpg",
      label: "collections",
      item: "vintage-vibes",
      color: "Maroon",
      size: "S",
      image: "/images/default.svg",
    },
    {
      id: 38,
      title: "Premium Collection Tee 2",
      subtitle: "Premium Collection",
      price: 1399,
      img: "/images/mock/product2.jpg",
      label: "collections",
      item: "premium-collection",
      color: "Navy",
      size: "XL",
      image: "/images/default.svg",
    },
    {
      id: 39,
      title: "Limited Edition Tee 2",
      subtitle: "Limited Edition",
      price: 1499,
      img: "/images/mock/product3.jpg",
      label: "collections",
      item: "limited-edition",
      color: "Black",
      size: "M",
      image: "/images/default.svg",
    },
    {
      id: 40,
      title: "All-Black Tee 2",
      subtitle: "Black",
      price: 799,
      img: "/images/mock/product4.jpg",
      label: "shop-by-color",
      item: "black",
      color: "Black",
      size: "S",
      image: "/images/default.svg",
    },
    {
      id: 41,
      title: "Pure White Tee 2",
      subtitle: "White",
      price: 799,
      img: "/images/mock/product1.jpg",
      label: "shop-by-color",
      item: "white",
      color: "White",
      size: "L",
      image: "/images/default.svg",
    },
    {
      id: 42,
      title: "Soft Neutral Tee 2",
      subtitle: "Neutrals",
      price: 849,
      img: "/images/mock/product2.jpg",
      label: "shop-by-color",
      item: "neutrals",
      color: "Beige",
      size: "M",
      image: "/images/default.svg",
    },
    {
      id: 43,
      title: "Earth Tone Tee 2",
      subtitle: "Earth Tones",
      price: 899,
      img: "/images/mock/product3.jpg",
      label: "shop-by-color",
      item: "earth-tones",
      color: "Olive",
      size: "XL",
      image: "/images/default.svg",
    },
    {
      id: 44,
      title: "Bright Pop Tee 2",
      subtitle: "Brights",
      price: 949,
      img: "/images/mock/product4.jpg",
      label: "shop-by-color",
      item: "brights",
      color: "Bright Blue",
      size: "S",
      image: "/images/default.svg",
    },
    {
      id: 45,
      title: "Everyday Comfort Tee 2",
      subtitle: "Everyday Wear",
      price: 699,
      img: "/images/mock/product1.jpg",
      label: "shop-by-occasion",
      item: "everyday-wear",
      color: "Grey",
      size: "L",
      image: "/images/default.svg",
    },
    {
      id: 46,
      title: "Night-Out Tee 2",
      subtitle: "Night Out",
      price: 999,
      img: "/images/mock/product2.jpg",
      label: "shop-by-occasion",
      item: "night-out",
      color: "Black",
      size: "M",
      image: "/images/default.svg",
    },
    {
      id: 47,
      title: "Smart Workwear Tee 2",
      subtitle: "Workwear",
      price: 1099,
      img: "/images/mock/product3.jpg",
      label: "shop-by-occasion",
      item: "workwear",
      color: "Navy",
      size: "S",
      image: "/images/default.svg",
    },
    {
      id: 48,
      title: "Chill Lounge Tee 2",
      subtitle: "Lounge / Home",
      price: 799,
      img: "/images/mock/product4.jpg",
      label: "shop-by-occasion",
      item: "lounge-home",
      color: "Beige",
      size: "XL",
      image: "/images/default.svg",
    },
    {
      id: 49,
      title: "Street Graphic Tee Extra 49",
      subtitle: "Graphic Tees",
      price: 1199,
      img: "/images/mock/product1.jpg",
      label: "styles",
      item: "graphic-tees",
      color: "Bright Red",
      size: "XXL",
      image: "/images/default.svg",
    },
    {
      id: 50,
      title: "Everyday Plain Tee Extra 50",
      subtitle: "Plain Tees",
      price: 1499,
      img: "/images/mock/product2.jpg",
      label: "styles",
      item: "plain-tees",
      color: "Navy",
      size: "XXL",
      image: "/images/default.svg",
    },
  ];
  export const PRODUCTS: Product[] = preProduct.map((p) => ({
  ...p,
  image: `/images/${IMAGE_POOL[Math.floor(Math.random() * IMAGE_POOL.length)]}`,
}));